language: groovy
sudo: false
dist: trusty
jdk:
  - openjdk8
cache:
  directories:
  - $HOME/.gradle
before_install:
  - cd gradle-lombok-plugin
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./.travis-publishOnRelease.sh
